# Global configurations
dataroot: ./data/brain_tumor_mri_fake/brain_tumor_mri_circle_gray_huge
name: CNNonBrainMRI_Cir_Gray_Huge
gpu_ids: '0'
model: cnn
dataset_name: braintumormri
use_wandb: False

# Model configurations
input_nc: 3
num_classes: 2
phase: test 
eval: True
serial_batches: True

# Test configurations
batch_size: 16

# Evaluation configurations
epoch: best
