# Global configurations
dataroot: ./data/pascal_voc_2012
name: Resnet50onPASCAL
gpu_ids: '0'
model: res_class
dataset_name: pascalvoc2012
use_wandb: False

# Model configurations
net_name: resnet50
input_nc: 3
num_classes: 20
phase: test
eval: True
loss_type: bcewithlogits

# Evaluation configurations
serial_batches: True
epoch: 14

# Test configurations
batch_size: 1