# Global configurations
dataroot: ./data/lisa_traffic_light
name: ResNet50onTrafficLight
gpu_ids: '-1'
model: res_class
dataset_name: lisa_traffic_light
use_wandb: False

# Model configurations
net_name: resnet50
input_nc: 3
num_classes: 2
phase: val
eval: True

# Evaluation configurations
serial_batches: True
epoch: best

# Test configurations
batch_size: 16