# Global configurations
dataroot: ./data/celeba
name: CNNonCelebA
gpu_ids: '0'
model: res_class
dataset_name: celeba
use_wandb: False

# Model configurations
net_name: resnet50
input_nc: 3
num_classes: 40
phase: val 
eval: True
serial_batches: True
loss_type: bcewithlogits

# Test configurations
batch_size: 16

# Evaluation configurations
epoch: best