# Global configurations
dataroot: ./data/brain_tumor_mri
name: ResNet50onBrainMRI
gpu_ids: '0'
model: res_class
dataset_name: braintumormri
use_wandb: False

# Model configurations
net_name: resnet50
input_nc: 3
num_classes: 4
phase: val 
eval: True

# Evaluation configurations
serial_batches: True
epoch: best

# Explanation configurations
explanation_name: gradient_shap
# index_explain: [0,1]
# Configuration for BHEM
seg_method: edge
n_segments: 500
approx: False