# Global configurations
dataroot: ./data/brain_tumor_mri
name: CNNonBrainMRI
gpu_ids: '0'
model: cnn
dataset_name: braintumormri
use_wandb: False

# Model configurations
input_nc: 3
num_classes: 4
phase: val
eval: True
serial_batches: True

# Evaluation configurations
epoch: best

# Explanation configurations
explanation_name: bhem
approx: False
# index_explain: [0,1]
# Configuration for BHEM
seg_method: edge
n_segments: 200
 