# Global configurations
dataroot: ./data/imagenets50
name: ResNet50onImageNetS50
gpu_ids: '0'
model: res_class
dataset_name: imagenets50
use_wandb: False

# Model configurations
net_name: resnet50
input_nc: 3
num_classes: 50
phase: val
eval: True

# Evaluation configurations
serial_batches: True
epoch: best

# Explanation configurations
explanation_name: bhem
# index_explain: [0,1]
# index_instance: [548,549]
# Configuration for BHEM
seg_method: edge
n_segments: 500
approx: True