# Global configurations
dataroot: ./data/tiny-imagenet
name: ResNet101onTinyImageNet
gpu_ids: '0'
model: res_class
dataset_name: tiny_imagenet
use_wandb: True

# Model configurations
net_name: resnet101
input_nc: 3
num_classes: 200

# Training configurations
batch_size: 128
lr: 0.00001
n_epochs: 5
n_epochs_decay: 10
loss_type: cross_entropy
save_epoch_freq: 1