# Global configurations
dataroot: ./data/arrow_fake
name: CNNonArrow
gpu_ids: '0'
model: cnn
dataset_name: arrow
use_wandb: False

# Model configurations
input_nc: 3
num_classes: 2
phase: test
eval: True
serial_batches: True 

# Evaluation configurations
epoch: 225

# Explanation configurations
explanation_name: bhem
# index_explain: [0,1]
# Configuration for BHEM
seg_method: slic
n_segments: 200
approx: False