# Global configurations
dataroot: ./data/arrow_fake
name: CNNonArrow
gpu_ids: '0'
model: cnn
dataset_name: arrow
use_wandb: False

# Model configurations
input_nc: 3
num_classes: 2
phase: test
eval: True
serial_batches: True

# Test configurations
batch_size: 16

# Evaluation configurations
epoch: 225
