# Global configurations
dataroot: ./data/lisa_traffic_light
name: ResNet18onTrafficLight
gpu_ids: '0'
model: res_class
dataset_name: lisa_traffic_light
use_wandb: True

# Model configurations
net_name: resnet18
input_nc: 3
num_classes: 2

# Training configurations
batch_size: 64
lr: 0.00001
n_epochs: 20
n_epochs_decay: 40
loss_type: cross_entropy
save_epoch_freq: 1