# Global configurations
dataroot: ./data/brain_tumor_mri_fake/brain_tumor_mri_circle_white
name: CNNonBrainMRI_Cir_White
gpu_ids: '0'
model: cnn
dataset_name: braintumormri
use_wandb: False

# Model configurations
input_nc: 3
num_classes: 2
phase: test
eval: True
serial_batches: True

# Evaluation configurations
epoch: best

# Explanation configurations
explanation_name: bhem
# index_explain: [0,1]
# Configuration for BHEM
n_segments: 64
approx: False