dataroot: ./data/arrow
name: CNNonArrow
gpu_ids: '0'
model: cnn
dataset_name: arrow

input_nc: 3
num_classes: 2
batch_size: 20
lr: 0.0001
n_epochs: 200
n_epochs_decay: 200
save_epoch_freq: 5

loss_type: cross_entropy

use_wandb: True