dataroot: ./data/brain_tumor_mri
name: CNNonBrainMRI
gpu_ids: '0'
model: cnn
dataset_name: braintumormri

input_nc: 3
num_classes: 2
batch_size: 2

use_wandb: False

phase: val
eval: True 
epoch: 20

# Explanation configurations
explanation_name: bhem
# index_explain: [0,1]
# Configuration for BHEM
n_segments: 10
approx: True