dataroot: ./data/arrow_fake
name: CNNonArrow
gpu_ids: '0'
model: cnn
dataset_name: arrow

input_nc: 3
num_classes: 2
batch_size: 2
lr: 0.0001
n_epochs: 40
n_epochs_decay: 40
save_epoch_freq: 1

loss_type: cross_entropy

use_wandb: False

phase: test
eval: True 
epoch: 225

# Explanation configurations
explanation_name: shap
index_explain: [0,1]

approx: True