# Global configurations
dataroot: ./data/processed_brain_tumor_mri
name: CNNonProcBrainMRI
gpu_ids: '0'
model: cnn
dataset_name: braintumormri
use_wandb: True

# Model configurations
input_nc: 3
num_classes: 4

# Training configurations
batch_size: 100
lr: 0.001
n_epochs: 50
n_epochs_decay: 50
loss_type: cross_entropy
save_epoch_freq: 1