# Global configurations
dataroot: ./data/brain_tumor_mri_crop
name: CNNonBrainMRI_Crop
gpu_ids: '0'
model: cnn
dataset_name: braintumormri
use_wandb: True

# Model configurations
input_nc: 3
num_classes: 4

# Training configurations
batch_size: 100
lr: 0.001
n_epochs: 50
n_epochs_decay: 50
loss_type: cross_entropy
save_epoch_freq: 1