# Global configurations
dataroot: ./data/tiny-imagenet
name: ResNet50onTinyImageNet
gpu_ids: '0'
model: res_class
dataset_name: tiny_imagenet
use_wandb: False

# Model configurations
net_name: resnet50
input_nc: 3
num_classes: 200
phase: val
eval: True

# Evaluation configurations
serial_batches: True
epoch: 9

# Test configurations
batch_size: 16