# Global configurations
dataroot: ./data/malaria
name: ResNet18onMalaria
gpu_ids: '0'
model: res_class
dataset_name: malaria
use_wandb: False

# Model configurations
net_name: resnet18
input_nc: 3
num_classes: 2
phase: val 
eval: True

# Evaluation configurations
serial_batches: True
epoch: best

# Explanation configurations
explanation_name: rise
# index_explain: [0,1]
# Configuration for BHEM
seg_method: edge
n_segments: 500
approx: False