# Global configurations
dataroot: ./data/imagenets50
name: ResNet18onImageNetS50
gpu_ids: '0'
model: res_class
dataset_name: imagenets50
use_wandb: False

# Model configurations
net_name: resnet18
input_nc: 3
num_classes: 50
phase: val
eval: True

# Evaluation configurations
serial_batches: True
epoch: best

# Test configurations
batch_size: 1